[build-systen]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
authors = [
    {name = "tiksan"}
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Games/Entertainment",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers"
]
dependencies = [
    "mongoengine~=0.26.0",
    "redis ~= 4.5.1"
]
description = "Reusable components for Tornium"
keywords = ["tornium"]
license = {file = "LICENSE"}
name = "tornium-commons"
version = "0.1.0"

[project.optional-dependencies]

[project.urls]
homepage = "https://tornium.com"
repository = "https://github.com/Tornium/tornium-commons"
changelog = "https://github.com/Tornium/tornium-commons/blob/master/CHANGELOG.adoc"

[tool.black]
line-length = 120

[tool.bandit]
exclude_dirs = ["./.git", "__pycache__", "./venv"]