name: Black

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: psf/black@23.6.0
              with:
                  options: "--line-length 120 --check"
                  src: "."
